### ISSUE TITLE
能更新适配下支付宝v10.1.20么

### ISSUE THREAD

**Issue by litangyu** [wuxiaosu/XposedManyMoney#1]

**Comment by wuxiaosu** [comment]
能，已更新，感谢支持。

**Comment by litangyu** [comment]
我一直看不太懂支付宝的代码结构，理不清而且找不到想要的hook点，您能给个教程或者稍微说说思路么？

**Comment by wuxiaosu** [comment]
QQ、支付宝的代码我都没有仔细看，因为其实这个功能很简单，但是看的出来几家的代码、框架风格差别很大，看你是想hook什么，从关键点找突破口吧。
